### PR TITLE
Add feature: combined label

### PR DESCRIPTION
**Pull request by codealliance**
changes: optionsLabel allows array of model attributes (fields) + new param optionsSeparator

purpose: use multiselect customLabel, where label is combined from multiple object values

usage: 
BelongsToManyField::make(__('Contact'), 'contact', Contact::class)->options(\App\Contact::all())->optionsLabel(['firstname','lastname'],' '),

### CODE REVIEW

**Comment by everestmx** [comment]
Why not used Mutators? https://laravel.com/docs/7.x/eloquent-mutators#defining-an-accessor

```
class Contact extends Model {
    // ...
    public function getFullNameAttribute(){
        return $this->firstname . " " . $this->lastname;
    }
}
```

And usage:
```
BelongsToManyField::make(__('Contact'), 'contact', Contact::class)->options(Contact::all())->optionsLabel('full_name'),
```

**Comment by codealliance** [comment]
good point
didnt work, i retry and clos this thanks!

**Comment by codealliance** [comment]
hello
i tried again
with your example and other attempts also didnt work
the labels remain empty.
i have nova 3.7.1
laravel 7.19.1

**Comment by codealliance** [comment]
I got it! appends missing

**Pull request closed without merging**
